# Generated by Django 5.2.4 on 2025-09-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='EVENTORGANAIZER',
        ),
        migrations.AddField(
            model_name='eventorganaizer',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='review',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shedule', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=100)),
                ('eventtype', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('EVENTORGANAIZER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventorganaizer')),
                ('REFREE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.refree')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('STUDENT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sportsevent')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='EVENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sportsevent'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
