# Generated by Django 5.2.4 on 2025-10-06 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_refree_remove_event_eventorganaizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sportsevent',
            name='shedule',
        ),
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('date', models.DateField(default='')),
                ('fromTime', models.TimeField(default='')),
                ('toTime', models.TimeField(default='')),
                ('EVENT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sportsevent')),
            ],
        ),
    ]
