# Generated by Django 5.2.4 on 2025-10-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_sportsevent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='ORGANAIZER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.eventorganaizer'),
        ),
    ]
