# Generated by Django 5.2.4 on 2025-10-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_shedule_organaizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
