# Generated by Django 5.2.4 on 2025-10-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_register_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='', max_length=500)),
                ('title', models.CharField(default='', max_length=100)),
                ('EVENTORGANIZER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.eventorganaizer')),
            ],
        ),
    ]
